# SPDX-FileCopyrightText: 2025 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "mxl-sys"
edition = "2024"
publish = false
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
libloading = { version = "0.8.9" }

[build-dependencies]
bindgen = { version = "0.72", features = ["experimental"] }
cmake = "0.1.54"

[features]
mxl-not-built = []
